baseURL = 'https://learn.whad.io/'
languageCode = 'en-us'
DefaultContentLanguage = 'en'
title = 'WHAD Academy'
theme = 'whad-theme'

[params.icon]
collection = 'fa-solid'
icon = 'fa-graduation-cap'

[params.author]
name = "Whad Team"

[caches]
[caches.images]
dir = ':cacheDir/images'
